import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const page = await browser.newPage({ viewport: { width: 1180, height: 1050 }, deviceScaleFactor: 2 })
const errors = []
page.on('pageerror', (e) => errors.push(String(e)))
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto('http://127.0.0.1:4173/', { waitUntil: 'networkidle' })
await page.waitForTimeout(1000)
await page.getByRole('button', { name: 'Lett', exact: true }).click()
await page.waitForTimeout(300)
await page.screenshot({ path: '/tmp/start.png' })
await page.locator('.cat-card').first().click()
await page.waitForTimeout(200)
await page.screenshot({ path: '/tmp/start-selected.png' })
await page.getByRole('button', { name: 'Start runden' }).click()
await page.waitForTimeout(800)
await page.screenshot({ path: '/tmp/play.png' })
await page.getByRole('button', { name: /Gi meg et hint/ }).first().click()
await page.getByRole('button', { name: /Første bokstav i fornavn/ }).first().click()
await page.waitForTimeout(300)
await page.screenshot({ path: '/tmp/hint.png' })
await page.getByRole('button', { name: 'Vis alle svarene' }).click()
await page.waitForTimeout(400)
await page.getByRole('button', { name: /Fun fact/ }).first().click()
await page.waitForTimeout(300)
await page.screenshot({ path: '/tmp/answers.png' })
await page.goto('http://127.0.0.1:4173/banken', { waitUntil: 'networkidle' })
await page.waitForTimeout(400)
await page.screenshot({ path: '/tmp/bank.png' })
await browser.close()
console.log('OK. Feil i konsollen:', errors.length ? errors : 'ingen')
